clean_the_data:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "/opt/airflow/data/raw_data.db"
      schema: main
      schema_directory: "/opt/airflow/data"
      schemas_and_paths:
        main: "/opt/airflow/data/raw_data.db" 